services:
  - type: web
    name: resume-builder
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: SECRET_KEY
        generateValue: true
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1" 