services:
  - type: web
    name: resume-builder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: SECRET_KEY
        generateValue: true 